[package]
name = "queue-prop"
version = "0.1.0"
authors = ["Simon Dickson <simonhdickson@users.noreply.github.com>"]
edition = "2018"

[dependencies]
quickcheck = "0.6"
rand = "0.4"
rand_derive = "0.3"
